sudo: required

language: rust

rust:
  - stable

service:
  - docker

script:
  - cargo test

after_success: |
  ./coverage.sh
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
