[package]
name = "mock-it"
version = "0.1.0"
authors = ["nathanielsimard <nathaniel.simard@outlook.com>"]
description = "Make mocking reliable"
repository = "https://github.com/nathanielsimard/mock-it"
license = "MIT"
readme="README.md"

[dependencies]

[dev-dependencies]
table-test = "0.2.0"