name: publish

on:
  push:
    tags:        
      - '*'

jobs:
  publish-mock-it_codegen:
    name: publish-mock-it_codegen
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: publish mock-it_codegen to crates.io
        run: ./ci/publish.sh mock-it_codegen
        env:
          CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-mock-it:
    needs: publish-mock-it_codegen
    name: publish-mock-it
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: publish mock-it to crates.io
        run: ./ci/publish.sh mock-it
        env:
          CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
